import { useTheme } from "next-themes";
import Head from "next/head";
import { useContext, useState } from "react";
import Projects from "../../components/organisms/projects";
import { StoreContext } from "../../store/store-context";

export default function ProjectsIndex() {
  const { theme = "system" } = useTheme();
  const { realProjects, explorationProjects } = useContext(StoreContext);
  const [searchFilter, setSearchFilter] = useState<any>();
  return (
    <section className="flex flex-col gap-y-8 w-full max-w-7xl mx-auto mt-24">
      <Head>
        <title>Chaton Satria Y | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/next/logo-${theme}.svg`} />
      </Head>
      <Projects
        dataRealProject={realProjects}
        dataExplorationProject={explorationProjects}
        searchFilter={searchFilter}
        searchValue={(searchValue) => setSearchFilter(searchValue)}
      />
    </section>
  );
}
