import { useTheme } from "next-themes";
import Head from "next/head";
import Projects from "../../components/organisms/projects";

export default function ProjectsIndex() {
  const { theme } = useTheme();
  return (
    <section className="flex flex-col gap-y-8 w-full max-w-7xl mx-auto mt-24">
      <Head>
        <title>Chaton Satria Y | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/next/logo-${theme}.svg`} />
      </Head>
      <Projects />
    </section>
  );
}
