import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import Home from "../components/organisms/home";

const HomeIndex: NextPage = () => {
  const { theme } = useTheme();
  return (
    <section>
      <Head>
        <title>Chaton Satria Y | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/next/logo-${theme}.svg`} />
      </Head>
      <Home />
    </section>
  );
};

export default HomeIndex;
