import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import { useContext, useState } from "react";
import Home from "../components/organisms/home";
import { StoreContext } from "../store/store-context";

const HomeIndex: NextPage = () => {
  const { theme } = useTheme();
  const { realProjects } = useContext(StoreContext);
  const [realSearch, setRealSearch] = useState("");
  return (
    <section>
      <Head>
        <title>Chaton Satria Y | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/next/logo-${theme}.svg`} />
      </Head>
      <Home
        data={realProjects}
        searchFilter={realSearch}
        searchValue={(value) => setRealSearch(value)}
      />
    </section>
  );
};

export default HomeIndex;
