import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/organisms/home/Banner";
import Projects from "../components/organisms/home/Projects";

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col gap-y-11 w-full">
        <Banner />
        <Projects />
      </section>
    </section>
  );
};

export default Home;
